export const STARS_NAMES = [
  "Sirius",
  "Alpha Centauri A",
  "Betelgeuse",
  "Rigel",
  "Vega",
  "Polaris",
  "Proxima Centauri",
  "Arcturus",
  "Capella",
  "Aldebaran",
  "Antares",
  "Spica",
  "Pollux",
  "Castor",
  "Regulus",
  "Deneb",
  "Altair",
  "Fomalhaut",
  "Achernar",
  "Hadar",
  "Canopus",
  "Gacrux",
  "Acrux",
  "Shaula",
  "Bellatrix",
  "Alnilam",
  "Alnitak",
  "Alnair",
  "Mimosa",
  "Regor",
  "Alioth",
  "Miaplacidus",
  "Alnath",
  "Adhara",
  "Rasalas",
  "Rastaban",
  "Sabik",
  "Samson",
  "Alkaid",
  "Almach",
  "Algol",
  "Alkaid Major",
  "Alkalurops",
  "Alkes",
  "Almach",
  "Al Na'ir",
  "Alnilam",
  "Al Nitak",
  "Al Rischa",
  "Al Rufida",
  "Alschain",
  "Al Tair",
  "Altair",
  "Althain",
  "Aludra",
  "Andromeda",
  "Ankaa",
  "Apex",
  "Argo Navis",
  "Ariel",
  "Ascella",
  "Aschere",
  "Asellus Australis",
  "Asellus Borealis",
  "Asellus Primus",
  "Asellus Secundus",
  "Asellus Tertius",
  "Asterope",
  "Atlas",
  "Avior",
  "Azha",
  "Baham",
  "Baten Kaitos",
  "Bede",
  "Beid",
  "Benatnash",
  "Benetnasch",
  "Bentu",
  "Beta Crucis",
  "Beta Hydrae",
  "Beta Persei",
  "Beta Serpentis",
  "Beta Tauri",
  "Biham",
  "Botein",
  "Brachium",
  "Caelum",
  "Calaris",
  "Camelopardalis",
  "Cancer",
  "Canes Venatici",
  "Canis Major",
  "Canis Minor",
  "Capricornus",
  "Carina",
  "Cassiopeia",
  "Castor",
  "Cebalrai",
  "Cenix",
  "Centaurus",
  "Cepheus",
  "Cetus",
  "Chamaeleon",
  "Chara",
  "Chauve-Souris",
  "Chi Orionis",
  "Cih",
  "Cignus",
  "Circinus",
  "Clavius",
  "Columba",
  "Coma Berenices",
  "Concordia",
  "Corona Australis",
  "Corona Borealis",
  "Corvus",
  "Crater",
  "Crona",
  "Crux",
  "Cygnus",
];
export const PLANET_NAMES = [
  "Merkür",
  "Venüs",
  "Dünya",
  "Mars",
  "Jüpiter",
  "Satürn",
  "Uranüs",
  "Neptün",
  "Ceres",
  "Plüton",
  "Haumea",
  "Makemake",
  "Eris",
  "Proxima Centauri b",
  "TRAPPIST-1e",
  "Kepler-186f",
  "Kepler-452b",
  "Gliese 581g",
  "55 Cancri e",
  "HD 189733 b",
  "CoRoT-7b",
  "WASP-12b",
  "KELT-9b",
  "HAT-P-11b",
  "Luyten's Star b",
  "Ross 128 b",
  "Teegarden's Star b",
  "Tau Ceti e",
  "Epsilon Eridani b",
  "Mu Arae c",
  "Gliese 667 Cc",
  "Wolf 1061c",
  "K2-18b",
  "TOI-700 d",
  "GJ 1214 b",
  "HD 219134 b",
  "51 Pegasi b",
  "Gliese 876 c",
  "HR 8799 e",
  "XO-3b",
  "HD 100546 b",
  "GQ Lupi b",
  "CT Cha b",
  "PDS 70b",
  "PSO J318.5−22",
  "2M1207b",
  "HR 2562 b",
  "Gliese 436 b",
  "HATS-7b",
  "KELT-1b",
  "WASP-17b",
  "WASP-33b",
  "Kepler-90i",
  "TRAPPIST-1f",
  "TRAPPIST-1g",
  "TRAPPIST-1h",
  "LHS 1140 b",
  "GJ 357 d",
  "Alpha Centauri Bb",
  "2006 RH120",
  "2010 TK7",
  "2014 MU69 (Arrokoth)",
  "3 Juno",
  "4 Vesta",
  "10 Hygiea",
  "16 Psyche",
  "21 Lutetia",
  "22 Kalliope",
  "31 Euphrosyne",
  "32 Pomona",
  "34 Circe",
  "35 Leukothea",
  "37 Fides",
  "38 Leda",
  "40 Harmonia",
  "41 Daphne",
  "42 Isis",
  "44 Nysa",
  "45 Eugenia",
  "46 Hestia",
  "48 Doris",
  "49 Pales",
  "50 Virginia",
  "51 Nemausa",
  "52 Europa",
  "53 Kalypso",
  "54 Alexandra",
  "55 Pandora",
  "57 Mneme",
  "58 Concordia",
  "59 Elfrida",
  "60 Echo",
  "61 Danae",
  "62 Erato",
  "63 Ausonia",
  "64 Angelina",
  "65 Cybele",
  "66 Maja",
  "69 Hesperia",
  "70 Panacea",
  "71 Niobe",
  "72 Feronia",
  "73 Clytia",
  "74 Galatea",
  "76 Freia",
  "77 Frigga",
  "78 Diana",
  "79 Eurynome",
  "80 Sappho",
  "81 Terpsichore",
  "82 Alkmene",
  "83 Beatrix",
  "84 Klio",
  "85 Io",
  "86 Semele",
  "87 Sylvia",
  "88 Thisbe",
  "89 Julia",
  "90 Antiope",
  "91 Aegina",
  "92 Undina",
  "93 Minerva",
  "94 Aurora",
  "95 Arethusa",
  "96 Andromache",
  "97 Klotho",
  "98 Ianthe",
  "99 Dike",
  "100 Hecate",
];
export const GALAXY_NAMES = [
  "Andromeda Galaksisi (M31)",
  "Samanyolu Galaksisi",
  "Messier 87 (M87)",
  "Bode Galaksisi (M81)",
  "Cigar Galaksisi (M82)",
  "Whirlpool Galaksisi (M51)",
  "Sombrero Galaksisi (M104)",
  "Black Eye Galaksisi (M64)",
  "Triangulum Galaksisi (M33)",
  "Centaurus A",
  "Large Magellanic Cloud (LMC)",
  "Small Magellanic Cloud (SMC)",
  "Hoag's Object",
  "Cartwheel Galaksisi",
  "Antennae Galaxies",
  "Tadpole Galaksisi",
  "Pinwheel Galaksisi (M101)",
  "Leo Triplet",
  "Fornax A",
  "Hercules A",
  "Cygnus A",
  "Virgo A (M87)",
  "Sculptor Galaksisi",
  "Backward Galaxy",
  "Barnard's Galaxy",
  "Bear's Paw Galaxy",
  "Butterfly Galaxies",
  "Carafe Group",
  "Carina Dwarf",
  "Cetus A",
  "Circinus Galaxy",
  "Coddington's Nebula",
  "Coma Cluster",
  "Coma Pinwheel Galaxy",
  "Comet Galaxy",
  "Copeland Septet",
  "Cosmos Redshift 7",
  "Draco Dwarf",
  "Eye of Sauron",
  "Eyes Galaxies",
  "Fath 703",
  "Fireworks Galaxy",
  "Fornax Dwarf",
  "Fourcade-Figueroa object",
  "Grus Quartet",
  "Hardcastle Nebula",
  "Helix Galaxy",
  "Holmberg I",
  "Holmberg II",
  "Holmberg III",
  "Holmberg IV",
  "Holmberg V",
  "Holmberg VI",
  "Holmberg VII",
  "Holmberg VIII",
  "Holmberg IX",
  "Horologium Dwarf",
  "Hydra A",
  "Integral Sign Galaxy",
  "Keenan's System",
  "Kowal's Object",
  "Leo I",
  "Leo II",
  "Leo III",
  "Lindsay-Shapley Ring",
  "Little Sombrero Galaxy",
  "Maffei I",
  "Maffei II",
  "Malin 1",
  "Mayall's Object",
  "McLeish's Object",
  "Medusa Merger",
  "Messier 110",
  "Messier 32",
  "Mice Galaxies",
  "Minkowski's Object",
  "Needle Galaxy",
  "NGC 1316",
  "NGC 2537",
  "NGC 3031",
  "NGC 3561",
  "NGC 4038/9",
  "NGC 4286",
  "NGC 4565",
  "NGC 5128",
  "NGC 5216",
  "NGC 7252",
  "NGC 7742",
  "Nix",
  "Odin",
  "Ogmios",
  "Omega Centauri (cluster, not galaxy)",
  "Ophiuchus",
  "Orion Nebula (star-forming region, not galaxy)",
  "Orpheus",
  "Pavo",
  "Pegasus",
  "Perseus",
  "Phoenix",
  "Pictor",
  "Pisces",
  "Piscis Austrinus",
  "Polaris",
  "Pollux",
  "Pomerania",
  "Pleiades (star cluster, not galaxy)",
  "Puppis",
  "Pyxis",
  "Quasar 3C 273",
];
